### ISSUE TITLE
Crash when browsing book

### ISSUE THREAD

**Issue by valveo** [williewillus/Aura-Cascade#8]
This happend few times in row. Log from latest crash:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.2.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 18.3.2016 12:04
Description: Rendering screen

java.lang.AbstractMethodError: pixlepix.auracascade.lexicon.GuiLexiconEntry.renderToolTip(Lnet/minecraft/item/ItemStack;II)V
	at pixlepix.auracascade.lexicon.page.MultiblockPage.renderScreen(MultiblockPage.java:124)
	at pixlepix.auracascade.lexicon.GuiLexiconEntry.func_73863_a(GuiLexiconEntry.java:162)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1104)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at pixlepix.auracascade.lexicon.page.MultiblockPage.renderScreen(MultiblockPage.java:124)
	at pixlepix.auracascade.lexicon.GuiLexiconEntry.func_73863_a(GuiLexiconEntry.java:162)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)

-- Screen render details --
Details:
	Screen name: pixlepix.auracascade.lexicon.GuiLexiconEntry
	Mouse location: Scaled: (386, 254). Absolute: (772, 628)
	Screen size: Scaled: (800, 569). Absolute: (1600, 1137). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['HNInfo'/689567, l='MpServer', x=-255,78, y=71,00, z=167,36]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 8,00,64,00,8,00 - World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4124177 game time, 46536 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 103 total; [EntityPig['Pig'/743434, l='MpServer', x=-290,47, y=63,00, z=194,44], EntityChicken['Chicken'/743433, l='MpServer', x=-294,66, y=62,47, z=200,88], EntityBat['Bat'/1219600, l='MpServer', x=-192,23, y=10,35, z=220,65], EntitySheep['Sheep'/743432, l='MpServer', x=-320,69, y=67,00, z=236,84], EntityCreeper['Creeper'/1219354, l='MpServer', x=-233,06, y=71,00, z=131,38], EntitySheep['Sheep'/743430, l='MpServer', x=-244,56, y=71,00, z=215,38], EntityItem['item.item.egg'/1219869, l='MpServer', x=-286,87, y=66,00, z=212,68], EntitySheep['Sheep'/1155072, l='MpServer', x=-185,19, y=65,00, z=187,81], EntityZombie['Zombie'/1219076, l='MpServer', x=-308,50, y=66,00, z=242,50], EntityPig['Pig'/743443, l='MpServer', x=-282,66, y=69,00, z=234,69], EntityChicken['Chicken'/743440, l='MpServer', x=-286,19, y=66,00, z=212,72], EntitySheep['Sheep'/743447, l='MpServer', x=-218,84, y=67,00, z=217,91], EntityBat['Bat'/1219599, l='MpServer', x=-274,75, y=22,10, z=110,50], EntityPig['Pig'/743445, l='MpServer', x=-290,00, y=67,00, z=219,59], EntityPig['Pig'/743444, l='MpServer', x=-304,16, y=66,00, z=222,09], EntityBat['Bat'/1219597, l='MpServer', x=-183,84, y=54,84, z=106,59], EntitySkeleton['Skeleton'/1219634, l='MpServer', x=-298,50, y=15,00, z=124,50], EntitySheep['Sheep'/743215, l='MpServer', x=-338,47, y=64,00, z=154,88], EntitySkeleton['Skeleton'/1219637, l='MpServer', x=-333,50, y=22,00, z=118,50], EntityAuraNode['Aura Node'/743202, l='MpServer', x=-358,50, y=82,50, z=123,50], EntityZombie['Zombie'/1218622, l='MpServer', x=-211,50, y=66,00, z=222,50], EntitySkeleton['Skeleton'/1219388, l='MpServer', x=-284,50, y=15,00, z=111,50], EntitySheep['Sheep'/743231, l='MpServer', x=-325,50, y=66,00, z=97,31], EntitySkeleton['Skeleton'/1219366, l='MpServer', x=-186,31, y=64,28, z=189,06], EntityPlayerSP['HNInfo'/689567, l='MpServer', x=-255,78, y=71,00, z=167,36], EntityZombie['Zombie'/1217320, l='MpServer', x=-208,50, y=72,00, z=93,50], EntitySpider['Spider'/1218348, l='MpServer', x=-198,50, y=71,00, z=122,50], EntityPig['Pig'/743476, l='MpServer', x=-304,03, y=67,00, z=238,91], EntityBat['Bat'/1219154, l='MpServer', x=-281,80, y=12,01, z=131,33], EntitySpider['Spider'/1219665, l='MpServer', x=-222,50, y=68,00, z=218,50], EntitySheep['Sheep'/743246, l='MpServer', x=-315,88, y=87,00, z=93,72], EntitySheep['Sheep'/1156444, l='MpServer', x=-182,34, y=68,00, z=236,53], EntitySheep['Sheep'/743236, l='MpServer', x=-331,47, y=63,00, z=146,16], EntitySkeleton['Skeleton'/1218112, l='MpServer', x=-219,09, y=63,00, z=138,44], EntityBat['Bat'/1217097, l='MpServer', x=-281,58, y=28,09, z=194,49], EntityBat['Bat'/1217650, l='MpServer', x=-274,72, y=56,14, z=174,49], EntityBat['Bat'/1219448, l='MpServer', x=-209,13, y=16,94, z=185,75], EntityAuraNode['Aura Node'/743271, l='MpServer', x=-280,50, y=77,50, z=26,50], EntitySheep['Sheep'/1156451, l='MpServer', x=-223,53, y=77,00, z=87,44], EntitySkeleton['Skeleton'/1219680, l='MpServer', x=-199,53, y=66,00, z=177,94], EntitySheep['Sheep'/1156450, l='MpServer', x=-217,53, y=72,00, z=93,72], EntitySheep['Sheep'/1156453, l='MpServer', x=-201,53, y=68,00, z=242,31], EntityCreeper['Creeper'/1219429, l='MpServer', x=-272,50, y=87,00, z=191,50], EntityCreeper['Creeper'/1219433, l='MpServer', x=-286,50, y=88,00, z=95,50], EntityCreeper['Creeper'/1218670, l='MpServer', x=-230,50, y=78,00, z=239,50], EntityBat['Bat'/1218412, l='MpServer', x=-174,99, y=51,00, z=206,83], EntityZombie['Zombie'/1218451, l='MpServer', x=-195,50, y=45,00, z=163,50], EntitySpider['Grim Spider'/1218963, l='MpServer', x=-217,50, y=70,00, z=239,50], EntityAuraNode['Aura Node'/1156508, l='MpServer', x=-179,50, y=99,50, z=291,50], EntityBat['Bat'/1219743, l='MpServer', x=-175,79, y=51,74, z=207,50], EntityZombie['Zombie'/1218946, l='MpServer', x=-247,50, y=78,00, z=211,50], EntityCreeper['Creeper'/1219723, l='MpServer', x=-180,50, y=55,00, z=206,50], EntityZombie['Zombie'/1219720, l='MpServer', x=-273,50, y=16,00, z=125,50], EntityEnderman['Enderman'/1217679, l='MpServer', x=-277,53, y=76,00, z=236,72], EntityBat['Bat'/1219771, l='MpServer', x=-321,55, y=19,66, z=120,46], EntityBat['Bat'/1219768, l='MpServer', x=-180,44, y=52,43, z=88,28], EntityBat['Bat'/1219513, l='MpServer', x=-318,46, y=20,31, z=122,47], EntityWitch['Witch'/1219006, l='MpServer', x=-304,50, y=58,00, z=141,50], EntityPig['Pig'/743359, l='MpServer', x=-294,94, y=64,00, z=186,16], EntitySheep['Sheep'/743358, l='MpServer', x=-291,47, y=62,59, z=191,00], EntityPig['Pig'/743357, l='MpServer', x=-291,97, y=62,53, z=189,25], EntityAuraNode['Aura Node'/1156518, l='MpServer', x=-299,50, y=80,50, z=290,50], EntityBat['Bat'/1219243, l='MpServer', x=-212,43, y=51,42, z=231,38], EntityZombie['Zombie'/1217199, l='MpServer', x=-235,50, y=68,00, z=224,50], EntityZombie['Zombie'/1194706, l='MpServer', x=-252,13, y=59,00, z=172,50], EntityItem['item.item.egg'/1216978, l='MpServer', x=-294,88, y=62,00, z=200,31], EntitySheep['Sheep'/743369, l='MpServer', x=-310,72, y=64,00, z=211,75], EntitySheep['Sheep'/1155287, l='MpServer', x=-227,59, y=73,00, z=236,66], EntitySheep['Sheep'/743373, l='MpServer', x=-319,22, y=64,00, z=210,09], EntitySheep['Sheep'/743372, l='MpServer', x=-219,16, y=67,00, z=219,84], EntitySheep['Sheep'/1155286, l='MpServer', x=-236,19, y=70,00, z=232,16], EntitySquid['Squid'/1218261, l='MpServer', x=-293,19, y=61,94, z=188,91], EntityZombie['Zombie'/1218264, l='MpServer', x=-241,50, y=35,00, z=183,50], EntityCreeper['Creeper'/1219800, l='MpServer', x=-315,50, y=65,00, z=193,50], EntityCreeper['Creeper'/1218780, l='MpServer', x=-194,06, y=66,00, z=167,56], EntityCreeper['Creeper'/1218756, l='MpServer', x=-267,06, y=88,00, z=100,59], EntityCreeper['Creeper'/1219013, l='MpServer', x=-181,84, y=70,00, z=147,16], EntityZombie['Zombie'/1219018, l='MpServer', x=-292,47, y=66,00, z=215,16], EntitySkeleton['Skeleton'/1218249, l='MpServer', x=-279,50, y=32,00, z=208,50], EntitySpider['Spider'/1219276, l='MpServer', x=-263,50, y=90,00, z=236,50], EntityChicken['Chicken'/743401, l='MpServer', x=-305,75, y=68,00, z=232,50], EntityRobot['Robot'/743405, l='MpServer', x=-244,50, y=58,31, z=200,50], EntitySheep['Sheep'/1155063, l='MpServer', x=-199,44, y=71,00, z=102,22], EntityCreeper['Creeper'/1218036, l='MpServer', x=-244,50, y=68,00, z=148,31], EntitySquid['Squid'/1219317, l='MpServer', x=-315,47, y=60,59, z=201,75], EntitySheep['Sheep'/1155064, l='MpServer', x=-208,53, y=71,00, z=114,66], EntityBat['Bat'/1219576, l='MpServer', x=-197,53, y=45,99, z=243,28], EntitySheep['Sheep'/1155066, l='MpServer', x=-183,19, y=67,00, z=211,34], EntitySheep['Sheep'/743399, l='MpServer', x=-197,59, y=67,00, z=220,97], EntitySheep['Sheep'/743397, l='MpServer', x=-335,50, y=63,00, z=217,81], EntitySheep['Sheep'/1155071, l='MpServer', x=-180,94, y=68,00, z=180,13], EntitySheep['Sheep'/1155070, l='MpServer', x=-190,38, y=64,58, z=188,69], EntityCow['Cow'/1147873, l='MpServer', x=-292,13, y=69,00, z=245,97], EntityPig['Pig'/1147875, l='MpServer', x=-280,66, y=71,00, z=240,16], EntitySheep['Sheep'/743422, l='MpServer', x=-218,78, y=67,00, z=214,53], EntitySheep['Sheep'/743421, l='MpServer', x=-230,16, y=68,00, z=220,44], EntityAuraNode['Aura Node'/743411, l='MpServer', x=-299,50, y=69,50, z=228,50], EntitySheep['Sheep'/743410, l='MpServer', x=-204,88, y=68,00, z=212,16], EntitySheep['Sheep'/743409, l='MpServer', x=-201,44, y=68,00, z=199,81], EntityPig['Pig'/743414, l='MpServer', x=-300,28, y=67,00, z=237,53], EntityChicken['Chicken'/743413, l='MpServer', x=-302,66, y=67,00, z=239,31], EntitySheep['Sheep'/743412, l='MpServer', x=-301,91, y=68,00, z=231,13], EntityZombie['Zombie'/1219821, l='MpServer', x=-206,42, y=71,00, z=132,11]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1383502608 bytes (1319 MB) / 4007657472 bytes (3822 MB) up to 4007657472 bytes (3822 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024M -Xmx4096M -XX:MaxPermSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJA	aura{592} [Aura Cascade] (AuraCascade-592.jar) 
	UCHIJA	bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
	UCHIJA	BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
	UCHIJA	BetterThanBunnies{1.8.9-1.0.1} [BetterThanBunnies] (BetterThanBunnies-1.8.9-1.0.1.jar) 
	UCHIJA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJA	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UCHIJA	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCHIJA	BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-19.jar) 
	UCHIJA	bookshelfapi{2.3.6} [Bookshelf] (Bookshelf-API-1.8.9-2.3.6.jar) 
	UCHIJA	Thaumcraft{5.2.2} [Thaumcraft] (Thaumcraft-1.8.9-5.2.2.jar) 
	UCHIJA	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCHIJA	BuildCraft|Core{7.2.0} [BuildCraft] (buildcraft-7.2.0.jar) 
	UCHIJA	BuildCraft|Builders{7.2.0} [BC Builders] (buildcraft-7.2.0.jar) 
	UCHIJA	BuildCraft|Transport{7.2.0} [BC Transport] (buildcraft-7.2.0.jar) 
	UCHIJA	BuildCraft|Energy{7.2.0} [BC Energy] (buildcraft-7.2.0.jar) 
	UCHIJA	BuildCraft|Silicon{7.2.0} [BC Silicon] (buildcraft-7.2.0.jar) 
	UCHIJA	BuildCraft|Robotics{7.2.0} [BC Robotics] (buildcraft-7.2.0.jar) 
	UCHIJA	BuildCraft|Factory{7.2.0} [BC Factory] (buildcraft-7.2.0.jar) 
	UCHIJA	buildingbrickscompatvanilla{1.8.9-1.4.1} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.4.1.jar) 
	UCHIJA	buildingbricks{1.8.9-1.4.1} [Building Bricks] (BuildingBricks-1.8.9-1.4.1.jar) 
	UCHIJA	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJA	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
	UCHIJA	CharsetLib{0.2.4} [‽] (Charset-0.2.4-85343416c852285a595c4c6e.jar) 
	UCHIJA	CharsetTweaks{0.2.4} [*] (Charset-0.2.4-85343416c852285a595c4c6e.jar) 
	UCHIJA	CharsetDrama{0.2.4} [!] (Charset-0.2.4-85343416c852285a595c4c6e.jar) 
	UCHIJA	CharsetWires{0.2.4} [+] (Charset-0.2.4-85343416c852285a595c4c6e.jar) 
	UCHIJA	CharsetAudio{0.2.4} [♫] (Charset-0.2.4-85343416c852285a595c4c6e.jar) 
	UCHIJA	CharsetStorage{0.2.4} [#] (Charset-0.2.4-85343416c852285a595c4c6e.jar) 
	UCHIJA	CharsetPipes{0.2.4} [|] (Charset-0.2.4-85343416c852285a595c4c6e.jar) 
	UCHIJA	CharsetGates{0.2.4} [&] (Charset-0.2.4-85343416c852285a595c4c6e.jar) 
	UCHIJA	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCHIJA	chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
	UCHIJA	compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar) 
	UCHIJA	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UCHIJA	craftingtweaks{3.0.52} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.52.jar) 
	UCHIJA	crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-1.8.8-3.0.2.jar) 
	UCHIJA	dsurround{2.0.4.10} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.4.10.jar) 
	UCHIJA	ShetiPhianCore{3.1.0} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.0.jar) 
	UCHIJA	EnderTanks{1.2.1} [EnderTanks] (EnderTanks-1.8.9-1.2.1.jar) 
	UCHIJA	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.6.jar) 
	UCHIJA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJA	flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.8.jar) 
	UCHIJA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJA	furnus{1.73} [Furnus] (Furnus-1.8.9-1.73.jar) 
	UCHIJA	graves{1.8.9-b45-universal} [Graves Mod] (graves-1.8.9-b45-universal.jar) 
	UCHIJA	hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
	UCHIJA	k4lib{1.8.9-1.0.16} [K4Lib] (k4lib-1.8.9-1.0.16-universal.jar) 
	UCHIJA	HydCraft{1.8.9-3.1.79} [Hydraulicraft] (HydCraft-1.8.9-3.1.79-universal.jar) 
	UCHIJA	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UCHIJA	inventorysorter{0.7.4+26} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.4+26.jar) 
	UCHIJA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJA	llor{1.0.5-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.5-mc1.8.9.jar) 
	UCHIJA	mantle{1.8.9-0.8.2.jenkins95} [Mantle] (Mantle-1.8.9-0.8.2.jar) 
	UCHIJA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJA	Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
	UCHIJA	MouseTweaks{2.6.0} [Mouse Tweaks] (MouseTweaks-2.6.0-mc1.8.9.jar) 
	UCHIJA	tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct] (TConstruct-1.8.9-2.1.0.jar) 
	UCHIJA	neotech{2.4.1} [NeoTech] (NeoTech-1.8.9-2.4.1.jar) 
	UCHIJA	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar) 
	UCHIJA	fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
	UCHIJA	playerrugs{0.0.1} [Player Rugs] (PlayerRugs-1.8.8-1.2.0.jar) 
	UCHIJA	PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
	UCHIJA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJA	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCHIJA	RandomThings{3.6.4} [Random Things] (RandomThings-MC1.8.9-3.6.4.jar) 
	UCHIJA	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	UCHIJA	rftools{4.22beta31} [RFTools] (rftools-1.8.9-4.22beta31.jar) 
	UCHIJA	simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
	UCHIJA	soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
	UCHIJA	StorageDrawers{1.8.9-2.4.4} [Storage Drawers] (StorageDrawers-1.8.9-2.4.4.jar) 
	UCHIJA	thaumicinfusion{4.82} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.82.jar) 
	UCHIJA	wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
	UCHIJA	denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.0.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  lumien.randomthings.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.2.jar)
  
dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5800 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5800 Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7700K Radeon R7, 10 Compute Cores 4C+6G

**Comment by vcordie** [comment]
Same problem, though my crash occurs when hoverig over a block in a "demonstrating blocks in world" part of the lexicon, such as page 2 of the power basics page in the walkthrough chapter. http://paste.ee/p/Atlza contains crashlog

**Comment by BBoldt** [comment]
https://github.com/BBoldt/ThePioneers/issues/65
